#! /bin/bash
sudo cat <<EOF> /etc/nginx/sites-available/orienta_web
server{
listen 80;
listen [::]:80;
root /var/www/orienta_web;
index index.html index.php;
server_name orienta-webserver;
location / {
try_files $uri $uri/ =404;
}
location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
}
location ~ /\.ht {
        deny all;
}
}
EOF
